### ISSUE TITLE
Use Github Tokens instead of Passwords

### ISSUE THREAD

**Issue by alichtman** [mtn/mkgist#4]
It's a good practice to use API Tokens instead of passwords. 

Check out [this GitHub blog post](https://blog.github.com/2013-05-16-personal-api-tokens/) for the rationale 

I would improve this by changing all references from `password` to `github_token` or `GITHUB_TOKEN`.

**Comment by mtn** [comment]
Hm, thanks for bringing this up. The original reason I didn't do anything more complex for authentication was mostly laziness, so I'm definitely open to changing it. I'm not sure this would do much though -- `mkgist` doesn't store your credentials anywhere off your own computer (or outside your home directory, this is easy to verify since the source is pretty small). So I'm not sure being able to revoke tokens is much of a benefit. I think the token might also allow you to restrict scopes, but again I think it's easy enough to verify the script does what it says.

So I'm thinking that the cost of using these tokens is that it'd complicate setup (since afaik, you have to obtain these tokens through the GUI), but none of the benefits would be very useful. Feel free to push back.

I think something like OAuth could be more appropriate. Thoughts?

**Comment by alichtman** [comment]
> mkgist doesn't store your credentials anywhere off your own computer (or outside your home directory, this is easy to verify since the source is pretty small)

There's a security theory called [Least Privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege) that essentially says each part of a system should have the minimum necessary level of power. If it's ever compromised, you limit the amount of damage possible. 

The password used by `mkgist` is a plaintext GitHub password, which means that if the file is ever compromised (and a lot of devs run systems that aren't completely secure), full and total access to a GitHub account would be granted. I believe that the Token can only stand as a replacement for the login password (but I'm not 100% sure), and not the "confirm you're about to do something dangerous, like delete a repo or add a user to an organization" authentication. If it can, then I agree that it's not worthwhile. Otherwise, I see it as a great risk management action.

**Comment by mtn** [comment]
You're right, and it does allow you to restrict scopes and is definitely useful. I'll swap it out.

**Comment by mtn** [comment]
This should be done, and pip should be serving a version that relies on authentication tokens soon. I guess on second thought it'll fail if a old conf exists, so I'm going to fix that as well. And there are a probably a few other places I should make sure things don't crash. But no more credentials :-)

**Comment by mtn** [comment]
Alright, version `3.2` implements this (my semantic versioning leaves much to be desired, but I blame `pypi`). Should be served by `pip` sometime within the next 20 minutes.
